feat(location): adding battery level data
sailing-yacht-research-foundation/client-sdk-ios-swift pull request #9
Opened 2022-04-20 16:02 UTC by namchuai

- Adding battery level to each location update.

2022-04-21 08:14 UTC, radurad requested changes

2022-04-21 08:14 UTC, radurad commented on SYRFLocation/SYRFLocation/Data/LocationData.swift
> +        self.batteryLevel = Double(UIDevice.current.batteryLevel)
Using batteryLevel directly without requesting monitoring will yield a -1.0 value always as stated here: https://developer.apple.com/documentation/uikit/uidevice/1620042-batterylevel?language=objc

You'll have to explicitly request notification or read capability for the battery as stated here: https://developer.apple.com/documentation/uikit/uidevice/1620045-batterymonitoringenabled?language=objc.

If battery level is the only new addition then we can tie it up with start/stopLocationUpdates, whenever called, enabled/disable battery monitoring. If there are other readings that we need to extract apart from the battery level, we should consider creating a dedicated manager for them as well.

2022-04-21 08:17 UTC, namchuai commented on SYRFLocation/SYRFLocation/Data/LocationData.swift
> +        self.batteryLevel = Double(UIDevice.current.batteryLevel)
omg, Sorry @radurad , I misread that part. I will update the PR. Thanks for pointing it out!

2022-04-21 13:56 UTC, namchuai commented on SYRFLocation/SYRFLocation/Data/LocationData.swift
> +        self.batteryLevel = Double(UIDevice.current.batteryLevel)
@radurad , I updated the PR to add the enable/disable battery monitoring. Thanks!

2022-04-22 10:44 UTC, namchuai commented
closing to separate module

2022-04-22 10:44 UTC, closed without merging